# Processing TextDetox_dataset

In [5]:
import os
!huggingface-cli login

Warning: `huggingface-cli` is deprecated and no longer works. Use `hf` instead.

Hint: `hf` is already installed! Use it directly.

Hint: Examples:
  hf auth login
  hf download unsloth/gemma-4-31B-it-GGUF
  hf upload my-cool-model . .
  hf models ls --search "gemma"
  hf repos ls --format json
  hf jobs run python:3.12 python -c 'print("Hello!")'
  hf --help

In [11]:
from datasets import load_dataset

ds = load_dataset("textdetox/multilingual_toxicity_dataset")

README.md: 0.00B [00:00, ?B/s]

data/en-00000-of-00001.parquet:   0%|          | 0.00/267k [00:00<?, ?B/s]

data/ru-00000-of-00001.parquet:   0%|          | 0.00/388k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/uk-00000-of-00001.parquet:   0%|          | 0.00/360k [00:00<?, ?B/s]

data/de-00000-of-00001.parquet:   0%|          | 0.00/614k [00:00<?, ?B/s]

data/es-00000-of-00001.parquet:   0%|          | 0.00/641k [00:00<?, ?B/s]

data/am-00000-of-00001.parquet:   0%|          | 0.00/607k [00:00<?, ?B/s]

data/zh-00000-of-00001.parquet:   0%|          | 0.00/248k [00:00<?, ?B/s]

data/ar-00000-of-00001.parquet:   0%|          | 0.00/503k [00:00<?, ?B/s]

data/hi-00000-of-00001.parquet:   0%|          | 0.00/800k [00:00<?, ?B/s]

data/it-00000-of-00001.parquet:   0%|          | 0.00/522k [00:00<?, ?B/s]

data/fr-00000-of-00001.parquet:   0%|          | 0.00/388k [00:00<?, ?B/s]

data/he-00000-of-00001.parquet:   0%|          | 0.00/129k [00:00<?, ?B/s]

data/hin-00000-of-00001.parquet:   0%|          | 0.00/473k [00:00<?, ?B/s]

data/tt-00000-of-00001.parquet:   0%|          | 0.00/411k [00:00<?, ?B/s]

data/ja-00000-of-00001.parquet:   0%|          | 0.00/451k [00:00<?, ?B/s]

Generating en split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating ru split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating uk split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating de split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating es split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating am split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating zh split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating ar split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating hi split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating it split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating fr split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating he split:   0%|          | 0/2011 [00:00<?, ? examples/s]

Generating hin split:   0%|          | 0/4363 [00:00<?, ? examples/s]

Generating tt split:   0%|          | 0/5000 [00:00<?, ? examples/s]

Generating ja split:   0%|          | 0/5000 [00:00<?, ? examples/s]

In [83]:
import pandas as pd

df = pd.concat(
    [ds[lang].to_pandas() for lang in ds.keys()],
    ignore_index=True
)

In [84]:
df.head()

                                                text  toxic
0  The trans women reading this tweet right now i...      0
1  9) uhhhh i like being lgbt a lot. i feel proud...      0
2               Hero Rohit Sharma love From Pakistan      0
3  As a slightly feminine top I appreciate all ma...      0
4  Delon Love Turkey and brave Turks from Indian ...      0

In [21]:
df.shape

(71374, 2)

In [85]:
print(df["toxic"].value_counts())

toxic
0    35867
1    35507
Name: count, dtype: int64

In [86]:
df["label"] = df["toxic"]

In [71]:
df.head()

                                                text  toxic  label
0  The trans women reading this tweet right now i...      0      0
1  9) uhhhh i like being lgbt a lot. i feel proud...      0      0
2               Hero Rohit Sharma love From Pakistan      0      0
3  As a slightly feminine top I appreciate all ma...      0      0
4  Delon Love Turkey and brave Turks from Indian ...      0      0

In [87]:
df = df[["text","label"]]

# Processing Combined_Hate_dataset (Hinglish)

In [88]:
df1 = pd.read_csv("combined_hate_speech_dataset.csv")
df1.shape

(29550, 9)

In [89]:
df1.head()

,text,hate_label,source,profanity_score,language,dataset_version,combined_date,text_length,word_count
0,Knowing ki Vikas kitna samjhata hai Priyanka a...,0,hate_speech_tsv,0,hinglish,v1.0,2025-09-11,126,25
1,I am Muhajir .. Aur mere lye sab se Pehly Paki...,0,hate_speech_tsv,0,hinglish,v1.0,2025-09-11,196,41
2,Doctor sab sahi me ke PhD (in hate politics) ...,0,hate_speech_tsv,0,hinglish,v1.0,2025-09-11,166,29
3,Poore Desh me Patel OBC me aate Hain sirf gujr...,0,hate_speech_tsv,0,hinglish,v1.0,2025-09-11,257,49
4,Sarkar banne ke bad Hindu hit me ek bhi faisla...,1,hate_speech_tsv,0,hinglish,v1.0,2025-09-11,140,25

In [90]:
df1 = df1[["text", "hate_label"]]

In [91]:
df1.head()

                                                text  hate_label
0  Knowing ki Vikas kitna samjhata hai Priyanka a...           0
1  I am Muhajir .. Aur mere lye sab se Pehly Paki...           0
2  Doctor  sab sahi me ke PhD (in hate politics) ...           0
3  Poore Desh me Patel OBC me aate Hain sirf gujr...           0
4  Sarkar banne ke bad Hindu hit me ek bhi faisla...           1

In [92]:
print(df1["hate_label"].value_counts())

hate_label
0    15825
1    13725
Name: count, dtype: int64

In [93]:
df1["label"] = df1["hate_label"]

In [94]:
df1 = df1[["text","label"]]

# Processing Hinglish_cyberbullying_dataset

In [95]:
df2 = pd.read_csv("hinglish_cyberbullying_dataset_25000.csv")
df2.shape

(25000, 3)

In [96]:
df2.head()

   ID                                 Text  Label
0   1                      You're awesome!      0
1   2  Tum jaise logon se baat nahi karte.      1
2   3        Thanks for your support yaar.      0
3   4     Teri aukaat kya hai samjhta hai?      1
4   5           Nice effort, proud of you.      0

In [97]:
print(df2["Label"].value_counts())

Label
1    15000
0    10000
Name: count, dtype: int64

In [98]:
df2["label"] = df2["Label"]
df2["text"] = df2["Text"]
df2 = df2[["text", "label"]]

# Processing train.csv

In [59]:
df3 = pd.read_csv("train.csv")
df3.shape

(159571, 8)

In [60]:
df3.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [61]:
toxicity_cols = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
df3['label'] = df3[toxicity_cols].any(axis=1).astype(int)

print(df3['label'].value_counts())
display(df3.head())

label
0    143346
1     16225
Name: count, dtype: int64

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,label
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,0

In [99]:
df3 = df3[["comment_text", "label"]]
df3["text"] = df3["comment_text"]
df3 = df3[["text", "label"]]

In [100]:
df3.head()

                                                text  label
0  Explanation\nWhy the edits made under my usern...      0
1  D'aww! He matches this background colour I'm s...      0
2  Hey man, I'm really not trying to edit war. It...      0
3  "\nMore\nI can't make any real suggestions on ...      0
4  You, sir, are my hero. Any chance you remember...      0

In [101]:
import pandas as pd
from sklearn.utils import resample
jigsaw_safe = df3[df3["label"] == 0]
jigsaw_toxic = df3[df3["label"] == 1]

target = len(jigsaw_toxic)

jigsaw_safe_bal = resample(
    jigsaw_safe,
    replace=False,
    n_samples=target,
    random_state=42
)

jigsaw_bal = pd.concat([jigsaw_safe_bal, jigsaw_toxic])
jigsaw_bal = jigsaw_bal.sample(frac=1, random_state=42).reset_index(drop=True)

In [102]:
print(jigsaw_bal["label"].value_counts())

label
0    16225
1    16225
Name: count, dtype: int64

In [109]:
combined = pd.concat([df, df1, df2, jigsaw_bal], ignore_index=True)

In [110]:
combined.shape

(158374, 2)

In [111]:
combined.head()

                                                text  label
0  The trans women reading this tweet right now i...      0
1  9) uhhhh i like being lgbt a lot. i feel proud...      0
2               Hero Rohit Sharma love From Pakistan      0
3  As a slightly feminine top I appreciate all ma...      0
4  Delon Love Turkey and brave Turks from Indian ...      0

In [112]:
print(combined["label"].value_counts())

label
1    80457
0    77917
Name: count, dtype: int64

In [113]:
combined.to_csv("final_dataset.csv", index=False)

In [114]:
from google.colab import files
files.download("final_dataset.csv")

label
1    80457
0    77917
Name: count, dtype: int64